formatter = "JuliaFormatter"

[full_analysis]
auto_instantiate = false            # boolean, default: true

[diagnostic]
all_files = false                   # boolean, default: true

[[diagnostic.patterns]]
pattern = "no matching method found `copy!\\(::Random\\.TaskLocalRNG, ::Nothing\\)`"
match_by = "message"
match_type = "regex"
severity = "off"
